// === [ Identifiers ] =========================================================

// --- [ Global Identifiers ] --------------------------------------------------

GlobalIdent
	: global_ident
	<< &ast.GlobalIdent{Ident: astx.String($0)}, nil >>
;

// --- [ Local Identifiers ] ---------------------------------------------------

LocalIdent
	: local_ident
	<< &ast.LocalIdent{Ident: astx.String($0)}, nil >>
;

// --- [ Label Identifiers ] ---------------------------------------------------

LabelIdent
	: label_ident
	<< &ast.LabelIdent{Ident: astx.String($0)}, nil >>
;

// --- [ Attribute Group Identifiers ] -----------------------------------------

AttrGroupID
	: attr_group_id
	<< &ast.AttrGroupID{ID: astx.String($0)}, nil >>
;

// --- [ Comdat Identifiers ] --------------------------------------------------

ComdatName
	: comdat_name
	<< &ast.ComdatName{Name: astx.String($0)}, nil >>
;

// --- [ Metadata Identifiers ] ------------------------------------------------

MetadataName
	: metadata_name
	<< &ast.MetadataName{Name: astx.String($0)}, nil >>
;

MetadataID
	: metadata_id
	<< &ast.MetadataID{ID: astx.String($0)}, nil >>
;

