// --- [ Aggregate expressions ] -----------------------------------------------

ExtractValueExpr
	: "extractvalue" "(" Type Constant Indices ")"
;

InsertValueExpr
	: "insertvalue" "(" Type Constant "," Type Constant Indices ")"
;

