// === [ Instructions ] ========================================================

// https://llvm.org/docs/LangRef.html#instruction-reference

// ref: ParseInstruction

Instructions
	: empty
	| InstructionList
;

InstructionList
	: Instruction
	| InstructionList Instruction
;

Instruction
	// Instructions not producing values.
	: StoreInst OptCommaSepMetadataAttachmentList
	| FenceInst OptCommaSepMetadataAttachmentList
	| CmpXchgInst OptCommaSepMetadataAttachmentList
	| AtomicRMWInst OptCommaSepMetadataAttachmentList
	// Instructions producing values.
	| LocalIdent "=" ValueInstruction
	| ValueInstruction
;

ValueInstruction
	// Binary instructions
	: AddInst OptCommaSepMetadataAttachmentList
	| FAddInst OptCommaSepMetadataAttachmentList
	| SubInst OptCommaSepMetadataAttachmentList
	| FSubInst OptCommaSepMetadataAttachmentList
	| MulInst OptCommaSepMetadataAttachmentList
	| FMulInst OptCommaSepMetadataAttachmentList
	| UDivInst OptCommaSepMetadataAttachmentList
	| SDivInst OptCommaSepMetadataAttachmentList
	| FDivInst OptCommaSepMetadataAttachmentList
	| URemInst OptCommaSepMetadataAttachmentList
	| SRemInst OptCommaSepMetadataAttachmentList
	| FRemInst OptCommaSepMetadataAttachmentList
	// Bitwise instructions
	| ShlInst OptCommaSepMetadataAttachmentList
	| LShrInst OptCommaSepMetadataAttachmentList
	| AShrInst OptCommaSepMetadataAttachmentList
	| AndInst OptCommaSepMetadataAttachmentList
	| OrInst OptCommaSepMetadataAttachmentList
	| XorInst OptCommaSepMetadataAttachmentList
	// Vector instructions
	| ExtractElementInst OptCommaSepMetadataAttachmentList
	| InsertElementInst OptCommaSepMetadataAttachmentList
	| ShuffleVectorInst OptCommaSepMetadataAttachmentList
	// Aggregate instructions
	| ExtractValueInst OptCommaSepMetadataAttachmentList
	| InsertValueInst OptCommaSepMetadataAttachmentList
	// Memory instructions
	| AllocaInst OptCommaSepMetadataAttachmentList
	| LoadInst OptCommaSepMetadataAttachmentList
	| GetElementPtrInst OptCommaSepMetadataAttachmentList
	// Conversion instructions
	| TruncInst OptCommaSepMetadataAttachmentList
	| ZExtInst OptCommaSepMetadataAttachmentList
	| SExtInst OptCommaSepMetadataAttachmentList
	| FPTruncInst OptCommaSepMetadataAttachmentList
	| FPExtInst OptCommaSepMetadataAttachmentList
	| FPToUIInst OptCommaSepMetadataAttachmentList
	| FPToSIInst OptCommaSepMetadataAttachmentList
	| UIToFPInst OptCommaSepMetadataAttachmentList
	| SIToFPInst OptCommaSepMetadataAttachmentList
	| PtrToIntInst OptCommaSepMetadataAttachmentList
	| IntToPtrInst OptCommaSepMetadataAttachmentList
	| BitCastInst OptCommaSepMetadataAttachmentList
	| AddrSpaceCastInst OptCommaSepMetadataAttachmentList
	// Other instructions
	| ICmpInst OptCommaSepMetadataAttachmentList
	| FCmpInst OptCommaSepMetadataAttachmentList
	| PhiInst OptCommaSepMetadataAttachmentList
	| SelectInst OptCommaSepMetadataAttachmentList
	| CallInst OptCommaSepMetadataAttachmentList
	| VAArgInst OptCommaSepMetadataAttachmentList
	| LandingPadInst OptCommaSepMetadataAttachmentList
	| CatchPadInst OptCommaSepMetadataAttachmentList
	| CleanupPadInst OptCommaSepMetadataAttachmentList
;

