// === [ Basic blocks ] ========================================================

/*
ParseBasicBlock
*/

BasicBlockList
	: BasicBlock
	| BasicBlockList BasicBlock
;

BasicBlock
	: OptLabelIdent Instructions Terminator
;

OptLabelIdent
	: empty
	| LabelIdent
;

