// === [ Basic blocks ] ========================================================

// ref: ParseBasicBlock
//
//   ::= LabelStr? Instruction*

BasicBlockList
	: BasicBlock
	| BasicBlockList BasicBlock
;

BasicBlock
	: OptLabelIdent Instructions Terminator
;

OptLabelIdent
	: empty
	| LabelIdent
;

