/*
/// ParseOptionalAlignment
///   ::= empty
///   ::= 'align' 4
bool LLParser::ParseOptionalAlignment(unsigned &Alignment) {
*/

OptAlignment
	: empty
	| Alignment
;

Alignment
	: "align" int_lit
;

/*
/// ParseOptionalAddrSpace
///   := empty
///   := 'addrspace' '(' uint32 ')'
bool LLParser::ParseOptionalAddrSpace(unsigned &AddrSpace) {
*/

OptAddrSpace
	: empty
	| AddrSpace
;

AddrSpace
	: "addrspace" "(" int_lit ")"
;

