// Code generated by "stringer -linecomment -type BinOp"; DO NOT EDIT.

package ast

import "strconv"

const _BinOp_name = "addandmaxminnandorsubumaxuminxchgxor"

var _BinOp_index = [...]uint8{0, 3, 6, 9, 12, 16, 18, 21, 25, 29, 33, 36}

func (i BinOp) String() string {
	if i >= BinOp(len(_BinOp_index)-1) {
		return "BinOp(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _BinOp_name[_BinOp_index[i]:_BinOp_index[i+1]]
}
