// Code generated by "stringer -linecomment -type FloatType"; DO NOT EDIT.

package ast

import "strconv"

const _FloatType_name = "halffloatdoublex86_fp80fp128ppc_fp128"

var _FloatType_index = [...]uint8{0, 4, 9, 15, 23, 28, 37}

func (i FloatType) String() string {
	if i >= FloatType(len(_FloatType_index)-1) {
		return "FloatType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _FloatType_name[_FloatType_index[i]:_FloatType_index[i+1]]
}
