// Code generated by "stringer -linecomment -type ReturnAttr"; DO NOT EDIT.

package ast

import "strconv"

const _ReturnAttr_name = "inregReturnAttrNoAliasReturnAttrNonNullReturnAttrSignExtReturnAttrZeroExt"

var _ReturnAttr_index = [...]uint8{0, 5, 22, 39, 56, 73}

func (i ReturnAttr) String() string {
	if i >= ReturnAttr(len(_ReturnAttr_index)-1) {
		return "ReturnAttr(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ReturnAttr_name[_ReturnAttr_index[i]:_ReturnAttr_index[i+1]]
}
