// --- [ Target Definition ] ---------------------------------------------------

// https://llvm.org/docs/LangRef.html#target-triple
// https://llvm.org/docs/LangRef.html#data-layout

/*
/// toplevelentity
///   ::= 'target' 'triple' '=' STRINGCONSTANT
///   ::= 'target' 'datalayout' '=' STRINGCONSTANT
bool LLParser::ParseTargetDefinition() {
*/

TargetDefinition
	: "target" "triple" "=" string_lit
	| "target" "datalayout" "=" string_lit
;

