// --- [ Type Defintion ] ------------------------------------------------------

// https://llvm.org/docs/LangRef.html#structure-type

/*
/// ParseUnnamedType:
///   ::= LocalVarID '=' 'type' type
bool LLParser::ParseUnnamedType() {
*/

/*
/// toplevelentity
///   ::= LocalVar '=' 'type' type
bool LLParser::ParseNamedType() {
*/

/*
/// ParseStructDefinition - Parse a struct in a 'type' definition.
bool LLParser::ParseStructDefinition(SMLoc TypeLoc, StringRef Name,
*/

TypeDef
	: LocalIdent "=" "type" "opaque"
	| LocalIdent "=" "type" Type
;

