// ~~~ [ Comdat Definition ] ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

// https://llvm.org/docs/LangRef.html#langref-comdats

// ref: parseComdat

ComdatDef
	: ComdatName "=" "comdat" SelectionKind
	<< &ast.ComdatDef{Name: $0.(ast.ComdatName), Kind: $3.(ast.SelectionKind)}, nil >>
;

SelectionKind
	: "any"            << ast.SelectionKindAny, nil >>
	| "exactmatch"     << ast.SelectionKindExactMatch, nil >>
	| "largest"        << ast.SelectionKindLargest, nil >>
	| "noduplicates"   << ast.SelectionKindNoDuplicates, nil >>
	| "samesize"       << ast.SelectionKindSameSize, nil >>
;

