// --- [ Use-list Order Directives ] -------------------------------------------

// https://llvm.org/docs/LangRef.html#use-list-order-directives

// ref: ParseUseListOrder
//
//   ::= 'uselistorder' Type Value ',' UseListOrderIndexes
//  UseListOrderIndexes
//   ::= '{' uint32 (',' uint32)+ '}'

UseListOrders
	: empty
	| UseListOrderList
;

UseListOrderList
	: UseListOrder
	| UseListOrderList UseListOrder
;

UseListOrder
	: "uselistorder" Type Value "," "{" IndexList "}"
;

// ref: ParseUseListOrderBB
//
//   ::= 'uselistorder_bb' @foo ',' %bar ',' UseListOrderIndexes

UseListOrderBB
	: "uselistorder_bb" GlobalIdent "," LocalIdent "," "{" IndexList "}"
;

