// ~~~ [ Use-list Order Directives ] ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

// https://llvm.org/docs/LangRef.html#use-list-order-directives

// ref: ParseUseListOrder
//
//   ::= 'uselistorder' Type Value ',' UseListOrderIndexes
//  UseListOrderIndexes
//   ::= '{' uint32 (',' uint32)+ '}'

UseListOrders
	: empty
	| UseListOrderList
;

UseListOrderList
	: UseListOrder                    << astx.NewUseListOrderList($0) >>
	| UseListOrderList UseListOrder   << astx.AppendUseListOrder($0, $1) >>
;

UseListOrder
	: "uselistorder" Type Value "," "{" IndexList "}"   << astx.NewUseListOrder($1, $2, $5) >>
;

// ref: ParseUseListOrderBB
//
//   ::= 'uselistorder_bb' @foo ',' %bar ',' UseListOrderIndexes

UseListOrderBB
	: "uselistorder_bb" GlobalIdent "," LocalIdent "," "{" IndexList "}"   << astx.NewUseListOrder($1, $3, $6) >>
;

