// ~~~ [ Type Defintion ] ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

// https://llvm.org/docs/LangRef.html#structure-type

// ref: ParseUnnamedType
//
//   ::= LocalVarID '=' 'type' type

// ref: ParseNamedType
//
//   ::= LocalVar '=' 'type' type

TypeDef
	: LocalIdent "=" "type" OpaqueType
	<< &types.NamedType{Name: $0.(*ast.LocalIdent).Name, Type: $3.(types.Type)}, nil >>
	| LocalIdent "=" "type" Type
	<< &types.NamedType{Name: $0.(*ast.LocalIdent).Name, Type: $3.(types.Type)}, nil >>
;

