// ~~~ [ Comdat Definition ] ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

// https://llvm.org/docs/LangRef.html#langref-comdats

// ref: parseComdat

ComdatDef
	: ComdatName "=" "comdat" SelectionKind
	<< &ll.ComdatDef{Name: $0.(*ast.ComdatName).Name, Kind: $3.(ll.SelectionKind)}, nil >>
;

SelectionKind
	: "any"            << ll.SelectionKindAny, nil >>
	| "exactmatch"     << ll.SelectionKindExactMatch, nil >>
	| "largest"        << ll.SelectionKindLargest, nil >>
	| "noduplicates"   << ll.SelectionKindNoDuplicates, nil >>
	| "samesize"       << ll.SelectionKindSameSize, nil >>
;

